name: file

on:

  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
   
   build:
      
      runs-on: ubuntu-latest
    
      steps:
         
         - uses: action/checkout@v2
         
         - name: Restore Cache
           uses: actions/cache@v2
         
      
         - name: Change wrapper permissions
           uses: actions/wrapper@v2
           
         - name: Assemble Debug
        
           run: ./gradlew assembleDebug

         - name: Upload APK
           uses: actions/upload-artifact@v2
           
           with:
      
            name: apk
            path: app/build/outputs/apk/debug/**.apk
          
          
          
          
           
